"""Build a reproducible index for validation and benchmark artifacts."""
from __future__ import annotations

from dataclasses import dataclass
import datetime as _dt
import hashlib
import json
from pathlib import Path
from typing import Any

from . import __version__
from .attest import AttestationOptions, attest_report, _redact


@dataclass
class EvidenceOptions:
    include_documents: bool = True
    max_reports: int = 0


def build_evidence_index(root: str | Path, options: EvidenceOptions | None = None) -> dict[str, Any]:
    opts = options or EvidenceOptions()
    base = Path(root).resolve()
    if not base.exists():
        raise FileNotFoundError(f"evidence root does not exist: {base}")
    if not base.is_dir():
        raise NotADirectoryError(f"evidence root is not a directory: {base}")
    reports: list[dict[str, Any]] = []
    auxiliary: list[dict[str, Any]] = []
    documents: list[dict[str, Any]] = []
    skipped: list[dict[str, str]] = []

    for path in sorted(base.glob("*.json")):
        try:
            attestation = attest_report(path, AttestationOptions(max_failures=0))
        except Exception as exc:
            aux = _auxiliary_entry(path, base)
            if aux:
                auxiliary.append(aux)
            else:
                skipped.append({"path": _safe_rel(path, base), "reason": _redact(str(exc))})
            continue
        if opts.max_reports and len(reports) >= opts.max_reports:
            skipped.append({"path": _safe_rel(path, base), "reason": "max_reports limit reached"})
            continue
        reports.append(_report_entry(path, base, attestation))

    if opts.include_documents:
        for path in sorted(base.glob("*.md")):
            documents.append(_document_entry(path, base))

    total_samples = sum(_int(r.get("total_samples")) for r in reports)
    total_failed = sum(_int(r.get("failed")) for r in reports)
    score_values = [_float(r.get("overall_score")) for r in reports if r.get("overall_score") not in ("", None)]
    average_score = round(sum(score_values) / len(score_values), 1) if score_values else 0.0

    return {
        "schema": "agent-redteam-evidence-index/v1",
        "generated_at": _dt.datetime.now(_dt.UTC).replace(microsecond=0).isoformat().replace(
            "+00:00", "Z"
        ),
        "generator": {
            "name": "agent-redteam",
            "version": __version__,
        },
        "root": _redact(base.name),
        "summary": {
            "reports": len(reports),
            "auxiliary": len(auxiliary),
            "documents": len(documents),
            "skipped": len(skipped),
            "total_samples": total_samples,
            "total_failed": total_failed,
            "average_score": average_score,
        },
        "reports": reports,
        "auxiliary": auxiliary,
        "documents": documents,
        "skipped": skipped,
    }


def render_evidence_json(index: dict[str, Any]) -> str:
    return json.dumps(index, ensure_ascii=False, indent=2)


def render_evidence_markdown(index: dict[str, Any]) -> str:
    summary = index["summary"]
    lines = [
        "# Agent Redteam Evidence Index",
        "",
        f"- **Reports:** {summary['reports']}",
        f"- **Auxiliary JSON artifacts:** {summary.get('auxiliary', 0)}",
        f"- **Documents:** {summary['documents']}",
        f"- **Skipped JSON files:** {summary['skipped']}",
        f"- **Total samples:** {summary['total_samples']}",
        f"- **Total failed:** {summary['total_failed']}",
        f"- **Average score:** {summary['average_score']}/100",
        f"- **Generated by:** agent-redteam {index['generator']['version']}",
        "",
        "## Scan Reports",
        "",
        "| Path | Model | Score | Samples | Failed | Weakest Suite | SHA-256 |",
        "|------|-------|------:|--------:|-------:|---------------|---------|",
    ]
    for report in index["reports"]:
        lines.append(
            f"| `{report['path']}` | {_cell(report['model'])} | {report['overall_score']} | "
            f"{report['total_samples']} | {report['failed']} | {_cell(report['weakest_suite'])} | "
            f"`{report['raw_sha256'][:12]}` |"
        )

    if index.get("auxiliary"):
        lines.extend([
            "",
            "## Auxiliary JSON Artifacts",
            "",
            "| Path | Type | Records | Key Counts | SHA-256 |",
            "|------|------|--------:|------------|---------|",
        ])
        for item in index["auxiliary"]:
            lines.append(
                f"| `{item['path']}` | {_cell(item['artifact_type'])} | {item['records']} | "
                f"{_cell(_format_counts(item.get('counts', {})))} | `{item['sha256'][:12]}` |"
            )

    if index["documents"]:
        lines.extend(["", "## Narrative Documents", "", "| Path | Title | SHA-256 |", "|------|-------|---------|"])
        for doc in index["documents"]:
            lines.append(f"| `{doc['path']}` | {_cell(doc['title'])} | `{doc['sha256'][:12]}` |")

    if index["skipped"]:
        lines.extend(["", "## Skipped JSON Files", "", "| Path | Reason |", "|------|--------|"])
        for item in index["skipped"]:
            lines.append(f"| `{item['path']}` | {_cell(item['reason'])} |")

    lines.extend([
        "",
        "## Reproducibility Notes",
        "",
        "- SHA-256 values are computed from the raw artifact bytes.",
        "- Scan JSON may include terminal log prefixes; valid scan reports are extracted before summarization.",
        "- The index summarizes existing artifacts only; it does not prove provider identity or rerun scans.",
        "",
    ])
    return "\n".join(lines)


def write_evidence_index(index: dict[str, Any], output: str | Path, fmt: str) -> None:
    content = render_evidence_json(index) if fmt == "json" else render_evidence_markdown(index)
    Path(output).write_text(content, encoding="utf-8")


def _report_entry(path: Path, base: Path, attestation: dict[str, Any]) -> dict[str, Any]:
    score = attestation["score"]
    target = attestation["target"]
    source = attestation["source"]
    suites = attestation.get("suite_breakdown", [])
    weakest = suites[0]["name"] if suites else ""
    return {
        "path": _safe_rel(path, base),
        "model": _redact(str(target.get("model", ""))),
        "started_at": _redact(str(target.get("started_at", ""))),
        "finished_at": _redact(str(target.get("finished_at", ""))),
        "overall_score": score.get("overall", 0),
        "total_samples": score.get("total_samples", 0),
        "passed": score.get("passed", 0),
        "failed": score.get("failed", 0),
        "errors": score.get("errors", 0),
        "weakest_suite": _redact(str(weakest)),
        "raw_sha256": source.get("raw_sha256", ""),
        "canonical_sha256": source.get("canonical_sha256", ""),
        "json_was_extracted": source.get("json_was_extracted", False),
    }


def _document_entry(path: Path, base: Path) -> dict[str, Any]:
    raw = path.read_bytes()
    text = raw.decode("utf-8", errors="replace")
    return {
        "path": _safe_rel(path, base),
        "title": _redact(_first_title(text) or path.stem),
        "sha256": hashlib.sha256(raw).hexdigest(),
        "bytes": len(raw),
    }


def _auxiliary_entry(path: Path, base: Path) -> dict[str, Any] | None:
    raw = path.read_bytes()
    if not raw.strip():
        return None
    try:
        data = json.loads(raw.decode("utf-8", errors="replace"))
    except json.JSONDecodeError:
        return None

    if isinstance(data, dict) and isinstance(data.get("results"), list):
        rows = data["results"]
        return {
            "path": _safe_rel(path, base),
            "artifact_type": "multi_turn_batch",
            "model": _redact(str(data.get("model", ""))),
            "batch": data.get("batch", ""),
            "records": len(rows),
            "counts": _value_counts(rows, "verdict"),
            "sha256": hashlib.sha256(raw).hexdigest(),
        }

    if isinstance(data, list) and data and all(isinstance(item, dict) for item in data):
        keys = set().union(*(item.keys() for item in data))
        if {"strategy", "sample_id", "bypassed"}.issubset(keys):
            return {
                "path": _safe_rel(path, base),
                "artifact_type": "mutation_results",
                "records": len(data),
                "counts": {
                    "bypassed": sum(1 for item in data if item.get("bypassed") is True),
                    "blocked": sum(1 for item in data if item.get("bypassed") is False),
                    "errors": sum(1 for item in data if item.get("bypassed") is None),
                },
                "sha256": hashlib.sha256(raw).hexdigest(),
            }

    return None


def _value_counts(rows: list[dict[str, Any]], key: str) -> dict[str, int]:
    counts: dict[str, int] = {}
    for row in rows:
        value = _redact(str(row.get(key, "") or "unknown"))
        counts[value] = counts.get(value, 0) + 1
    return dict(sorted(counts.items(), key=lambda kv: (-kv[1], kv[0])))


def _format_counts(counts: dict[str, Any]) -> str:
    return ", ".join(f"{key}={value}" for key, value in counts.items()) or "none"


def _first_title(text: str) -> str:
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith("#"):
            return stripped.lstrip("#").strip()
    return ""


def _safe_rel(path: Path, base: Path) -> str:
    try:
        value = path.resolve().relative_to(base).as_posix()
    except ValueError:
        value = path.name
    return _redact(value)


def _cell(value: Any) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def _int(value: Any) -> int:
    try:
        return int(value)
    except (TypeError, ValueError):
        return 0


def _float(value: Any) -> float:
    try:
        return float(value)
    except (TypeError, ValueError):
        return 0.0
