"""Markdown report generator — human-readable detailed scan report."""
from __future__ import annotations
from ..core.result import ScanReport


def render_markdown(report: ScanReport) -> str:
    """Generate a detailed Markdown report."""
    lines = [
        f"# Agent Redteam Report — {report.target_model}",
        "",
        f"- **Overall Score**: {report.overall_score}/100",
        f"- **Total Samples**: {report.total_samples}",
        f"- **Passed**: {report.total_passed} | **Failed**: {report.total_failed}",
        f"- **Started**: {report.started_at}",
        f"- **Finished**: {report.finished_at}",
        "",
        "---",
        "",
        "## Suite Breakdown",
        "",
        "| Suite | OWASP | Score | Passed | Failed | Total |",
        "|-------|-------|------:|-------:|-------:|------:|",
    ]

    for suite in report.suites:
        owasp = ""
        if suite.samples:
            owasp = suite.samples[0].owasp
        score_str = f"{suite.score}" if suite.score >= 0 else "N/A"
        lines.append(
            f"| {suite.name} | {owasp} | {score_str} | "
            f"{suite.passed} | {suite.failed} | {suite.total} |"
        )

    # Failed samples detail
    failed = [
        s for suite in report.suites
        for s in suite.samples
        if s.verdict.value == "fail"
    ]
    if failed:
        lines.extend(["", "---", "", f"## Failed Attacks ({len(failed)})", ""])
        for i, s in enumerate(failed[:50], 1):  # Top 50
            lines.extend([
                f"### {i}. {s.sample_id} — {s.suite} ({s.severity})",
                "",
                f"**Attack:** {s.question}",
                "",
                f"**Expected:** {s.expected}",
                "",
                f"**Response:**",
                "```",
                s.response[:500],
                "```",
                "",
            ])

    lines.extend([
        "---",
        "",
        "*Generated by Agent Redteam*",
    ])
    return "\n".join(lines)
